/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as SignupImport } from './routes/signup';
import { Route as RoomViewImport } from './routes/roomView';
import { Route as LoginImport } from './routes/login';
import { Route as JoinRoomImport } from './routes/joinRoom';
import { Route as DashboardImport } from './routes/dashboard';
import { Route as CreatedRoomImport } from './routes/createdRoom';
import { Route as RoomRouteImport } from './routes/room/route';
import { Route as IndexImport } from './routes/index';
import { Route as RoomIdRouteImport } from './routes/room/$id/route';

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any);

const RoomViewRoute = RoomViewImport.update({
  id: '/roomView',
  path: '/roomView',
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const JoinRoomRoute = JoinRoomImport.update({
  id: '/joinRoom',
  path: '/joinRoom',
  getParentRoute: () => rootRoute,
} as any);

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any);

const CreatedRoomRoute = CreatedRoomImport.update({
  id: '/createdRoom',
  path: '/createdRoom',
  getParentRoute: () => rootRoute,
} as any);

const RoomRouteRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const RoomIdRouteRoute = RoomIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoomRouteRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/room': {
      id: '/room';
      path: '/room';
      fullPath: '/room';
      preLoaderRoute: typeof RoomRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/createdRoom': {
      id: '/createdRoom';
      path: '/createdRoom';
      fullPath: '/createdRoom';
      preLoaderRoute: typeof CreatedRoomImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    '/joinRoom': {
      id: '/joinRoom';
      path: '/joinRoom';
      fullPath: '/joinRoom';
      preLoaderRoute: typeof JoinRoomImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/roomView': {
      id: '/roomView';
      path: '/roomView';
      fullPath: '/roomView';
      preLoaderRoute: typeof RoomViewImport;
      parentRoute: typeof rootRoute;
    };
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupImport;
      parentRoute: typeof rootRoute;
    };
    '/room/$id': {
      id: '/room/$id';
      path: '/$id';
      fullPath: '/room/$id';
      preLoaderRoute: typeof RoomIdRouteImport;
      parentRoute: typeof RoomRouteImport;
    };
  }
}

// Create and export the route tree

interface RoomRouteRouteChildren {
  RoomIdRouteRoute: typeof RoomIdRouteRoute;
}

const RoomRouteRouteChildren: RoomRouteRouteChildren = {
  RoomIdRouteRoute: RoomIdRouteRoute,
};

const RoomRouteRouteWithChildren = RoomRouteRoute._addFileChildren(
  RoomRouteRouteChildren,
);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/room': typeof RoomRouteRouteWithChildren;
  '/createdRoom': typeof CreatedRoomRoute;
  '/dashboard': typeof DashboardRoute;
  '/joinRoom': typeof JoinRoomRoute;
  '/login': typeof LoginRoute;
  '/roomView': typeof RoomViewRoute;
  '/signup': typeof SignupRoute;
  '/room/$id': typeof RoomIdRouteRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/room': typeof RoomRouteRouteWithChildren;
  '/createdRoom': typeof CreatedRoomRoute;
  '/dashboard': typeof DashboardRoute;
  '/joinRoom': typeof JoinRoomRoute;
  '/login': typeof LoginRoute;
  '/roomView': typeof RoomViewRoute;
  '/signup': typeof SignupRoute;
  '/room/$id': typeof RoomIdRouteRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/room': typeof RoomRouteRouteWithChildren;
  '/createdRoom': typeof CreatedRoomRoute;
  '/dashboard': typeof DashboardRoute;
  '/joinRoom': typeof JoinRoomRoute;
  '/login': typeof LoginRoute;
  '/roomView': typeof RoomViewRoute;
  '/signup': typeof SignupRoute;
  '/room/$id': typeof RoomIdRouteRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/room'
    | '/createdRoom'
    | '/dashboard'
    | '/joinRoom'
    | '/login'
    | '/roomView'
    | '/signup'
    | '/room/$id';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/room'
    | '/createdRoom'
    | '/dashboard'
    | '/joinRoom'
    | '/login'
    | '/roomView'
    | '/signup'
    | '/room/$id';
  id:
    | '__root__'
    | '/'
    | '/room'
    | '/createdRoom'
    | '/dashboard'
    | '/joinRoom'
    | '/login'
    | '/roomView'
    | '/signup'
    | '/room/$id';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  RoomRouteRoute: typeof RoomRouteRouteWithChildren;
  CreatedRoomRoute: typeof CreatedRoomRoute;
  DashboardRoute: typeof DashboardRoute;
  JoinRoomRoute: typeof JoinRoomRoute;
  LoginRoute: typeof LoginRoute;
  RoomViewRoute: typeof RoomViewRoute;
  SignupRoute: typeof SignupRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRouteRoute: RoomRouteRouteWithChildren,
  CreatedRoomRoute: CreatedRoomRoute,
  DashboardRoute: DashboardRoute,
  JoinRoomRoute: JoinRoomRoute,
  LoginRoute: LoginRoute,
  RoomViewRoute: RoomViewRoute,
  SignupRoute: SignupRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/room",
        "/createdRoom",
        "/dashboard",
        "/joinRoom",
        "/login",
        "/roomView",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/room": {
      "filePath": "room/route.tsx",
      "children": [
        "/room/$id"
      ]
    },
    "/createdRoom": {
      "filePath": "createdRoom.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/joinRoom": {
      "filePath": "joinRoom.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/roomView": {
      "filePath": "roomView.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/room/$id": {
      "filePath": "room/$id/route.tsx",
      "parent": "/room"
    }
  }
}
ROUTE_MANIFEST_END */
